### ISSUE TITLE
ScraperException: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by vivekbsony** [blues-lab/google-play-scraper-py#13]
Hello,

ScraperException: TypeError: Cannot read property 'replace' of undefined
google-play-scraper/lib/mappers/details.js

Probably google-play-scraper needs to update to "version": "8.0.3",

**Comment by nsamarin** [comment]
Thanks for brining this to my attention. Let me try to fix this by updating the dependencies.

**Comment by nsamarin** [comment]
@vivekbsony, just fixed it in the latest commit: 3afe168992069b46eaa841b3bd2ba53f03173869
 
Thanks again for spotting it, and let me know if you encounter any other issues.
